# states.py

(
    MAIN_MENU,
    IMPORTER_COUNTRY,
    IMPORTER_CURRENCY,
    IMPORTER_CURRENCY_MANUAL,  # for when the user selects "Others"
    IMPORTER_AMOUNT,
    IMPORTER_COMMISSION_CHOICE,
    IMPORTER_INN,
    IMPORTER_PURPOSE,
    IMPORTER_PHONE,
    IMPORTER_PREVIEW,

    EXPORTER_COUNTRY,
    EXPORTER_AMOUNT,
    EXPORTER_CURRENCY,
    EXPORTER_PURPOSE,
    EXPORTER_COMMISSION_CHOICE,
    EXPORTER_SENDER_DETAILS,
    EXPORTER_RECEIVER_DETAILS,
    EXPORTER_PHONE,
    EXPORTER_PREVIEW,

    PHYSICAL_CHOICES,
    PHYSICAL_COUNTRY,
    PHYSICAL_AMOUNT,
    PHYSICAL_CURRENCY,
    PHYSICAL_COMMISSION_CHOICE,
    PHYSICAL_PHONE,
    PHYSICAL_PREVIEW,

    AGENT_SUBMENU,
    AGENT_FLOW,
    AGENT_IMPORTER_COUNTRY,
    AGENT_IMPORTER_AMOUNT,
    AGENT_IMPORTER_CURRENCY,
    AGENT_IMPORTER_COMMISSION_CHOICE,
    AGENT_IMPORTER_INN,
    AGENT_IMPORTER_PURPOSE,
    AGENT_IMPORTER_PHONE,
    AGENT_IMPORTER_PREVIEW,

    AGENT_EXPORTER_COUNTRY,   
    AGENT_EXPORTER_AMOUNT,
    AGENT_EXPORTER_CURRENCY,
    AGENT_EXPORTER_PURPOSE,
    AGENT_EXPORTER_COMMISSION_CHOICE,
    AGENT_EXPORTER_SENDER_DETAILS,
    AGENT_EXPORTER_RECEIVER_DETAILS,
    AGENT_EXPORTER_PHONE,
    AGENT_EXPORTER_PREVIEW
) = range(45)
